networks:
  network2:
    name: network2
services:
  nginx1:
    container_name: nginx1
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/robots.txt:/data/www/robots.txt
      - ./proxy/sitemap.xml:/data/www/sitemap.xml
      - ./proxy/conf:/etc/nginx/conf.d/default.conf
      - ./stroim_vmeste36.crt:/etc/ssl/stroim-vmeste36.crt
      - ./stroim_vmeste36.key:/etc/ssl/stroim-vmeste36.key
    networks:
      - network2
    depends_on:
      - flask1
  flask1:
    container_name: flask1
    image: sober21/stroi:1.07
    networks:
      - network2
